### ISSUE TITLE
malformed package reference in csproj when choosing to install UIExtenderEx

### ISSUE THREAD

**Issue by tizubythefizo** [BUTR/Bannerlord.Module.Template#115]
As the subject says, when choosing to install UIExtenderEx the package reference in the csproj is malformed which results in the project being unable to be loaded.

To reproduce, simply create a new project with that option enabled (in my case I had Harmony and MCM also enabled).

The generated line is

`<PackageReference Include="Bannerlord.UIExtenderEx" Version="2.3.0 IncludeAssets="compile" />`

It's failing to close out the "Version" attribute with a "

**Comment by Aragas** [comment]
Thanks for reporting this! Fixed, will be available soon!
