### ISSUE TITLE
The SDK 'Bannerlord.BUTRModule.Sdk/1.10.99' specified could not be found.

### ISSUE THREAD

**Issue by Aberro** [BUTR/Bannerlord.Module.Template#158]
I've tried to create a new project from template, but I get this error when I'm trying to open the project. I did run 'dotnet new install Bannerlord.Templates', and there were no errors, the version is 1.3.1.86. 
I've installed latest Dotnet SDK, Visual Studio version is 17.5.3.

**Comment by Aberro** [comment]
Also, GameBinariesFolder incorrectly identified as Gaming.Desktop.x64_Shipping_Client, when vortex is installed. Probably, you'd want to check for bannerlord.exe, instead of just the folder.

**Comment by Aragas** [comment]
The version issue is fixed!

**Comment by Aragas** [comment]
And I agree, checking for `Bannerlord.exe` should fix the issue
