### ISSUE TITLE
Mount & Blade II Bannerlord\bin\Gaming.Desktop.x64_Shipping_Client\Bannerlord.exe not found error when trying to launch

### ISSUE THREAD

**Issue by Cephas369** [BUTR/Bannerlord.Module.Template#159]
Even if i deselect the xbox support and leave the BLSE requirement disabled i get this error when trying to launch, also there is some issue with the new update that it will not recognize the assemblies directory when creating a new project, i have to set it manually on the .csproj file

**Comment by Aragas** [comment]
Try the latest template, it might have fixed the issue!

**Comment by Cephas369** [comment]
> Try the latest template, it might have fixed the issue!

Now it's working normally again, thank you for the fix
