### ISSUE TITLE
ReSharper "Cannot resolve symbol" Error After Changing supported-game-version.txt

### ISSUE THREAD

**Issue by tategotoazarasi** [BUTR/Bannerlord.Module.Template#164]
After modifying the supported-game-version.txt file to update the game version from v1.1.2 to v1.2.8, I encountered an issue where ReSharper is no longer recognizing symbols and is throwing a "Cannot resolve symbol" error. Despite this, Visual Studio still provides navigation to these symbol definitions, and the project builds successfully.

Attempted Fixes:
- Cleared ReSharper's cache.
- Disabled and then re-enabled ReSharper.
- Reinstalled ReSharper.
- None of these actions resolved the issue.

**Comment by Aragas** [comment]
It was RefAsmer from JetBrains doing bad quality reference assembly creation. We've fixed it by switching to another tool. Now all version should contain properly the types
