### ISSUE TITLE
Singleplayer/MultiplayerModule deprecated in favor of ModuleCategory

### ISSUE THREAD

**Issue by robinlahtinen** [BUTR/Bannerlord.Module.Template#78]
From the e1.8.0 beta patch notes:

```
<SingleplayerModule/> and <MultiplayerModule/> have been renamed to <ModuleCategory/>

The correct usage is now <ModuleCategory value="Singleplayer"/> or <ModuleCategory value="Multiplayer"/>

The default ModuleCategory is Singleplayer.
```

**Proposed fix:**

Change the deprecated SubModule.xml variables to `<ModuleCategory value="Singleplayer"/>` or just remove them and let the game default to singleplayer.

**Comment by Aragas** [comment]
Thanks for the suggestion! We'll remove the old tags entirely once e1.8.0 hits stable!
