### ISSUE TITLE
Bannerlord.Templates could not be installed.

### ISSUE THREAD

**Issue by HackingLutz** [BUTR/Bannerlord.Module.Template#89]
Every time I try to install the package via `dotnet new --install Bannerlord.Templates` I receive following Error in Powershell: `Bannerlord.Templates could not be installed, the package does not exist.`  
I have the latest dotnet SDK installed and can't find any way to resolve this issue on my own, maybe I lack in knowledge with Visual Studio and the whole dotnet thing.

**Comment by jrymer** [comment]
I had the same issue. I was able to download from here
https://www.nuget.org/packages/Bannerlord.Templates.

And then run `dotnet new install location\to\bannerlord.templates.1.3.1.71.nupkg`

Afterwards you should be able to `dotnet new blmodfx --help`
